# Generated by Django 3.2.7 on 2023-07-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_auto_20230727_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ('user__first_name',), 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
