# Generated by Django 3.2.7 on 2023-07-27 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_alter_aluno_options'),
        ('edu', '0002_alter_matricula_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['aluno__user__first_name'], 'verbose_name': 'Matricula de Aluno', 'verbose_name_plural': 'Matricula de Alunos'},
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='nome_aluno',
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comum_aluno', to='comum.aluno', verbose_name='Aluno'),
            preserve_default=False,
        ),
    ]
